-- AlterTable
ALTER TABLE "Book" ADD COLUMN     "id_user" INTEGER,
ALTER COLUMN "autor" DROP NOT NULL,
ALTER COLUMN "quantPage" DROP NOT NULL,
ALTER COLUMN "genero" DROP NOT NULL,
ALTER COLUMN "data_inicial" DROP NOT NULL,
ALTER COLUMN "data_inicial" SET DATA TYPE TEXT,
ALTER COLUMN "data_fim" DROP NOT NULL,
ALTER COLUMN "data_fim" SET DATA TYPE TEXT;

-- AddForeignKey
ALTER TABLE "Book" ADD CONSTRAINT "Book_id_user_fkey" FOREIGN KEY ("id_user") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
